### ISSUE TITLE
netmiko 4 causes the dispatcher to fail

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nornir-nautobot#55] opened 2022-07-20 18:03 UTC
Multiple users have had issues where the import statements need to be updated in dispatcher/default.py.

From:
```
from netmiko.ssh_exception import NetmikoAuthenticationException, NetmikoTimeoutException
```

To:
```
from netmiko import NetmikoAuthenticationException, NetmikoTimeoutException
```

**Comment by jeffkala** [comment] 2022-07-20 18:07
[Netmiko 4.0.0 Release](https://github.com/ktbyers/netmiko/releases/tag/v4.0.0)

**Comment by jeffkala** [comment] 2022-07-20 19:46
Users environment was set at
```
napalm==3.3.1
nornir-napalm==0.2.0
netmiko==4.1.1
nornir-netmiko==0.2.0
```

**Comment by mzbroch** [comment] 2022-07-29 08:20
@jvanderaa We need to downgrade nornir-netmiko to 0.1.2 - current 0* impacts other plugin and builds.

**Comment by jvanderaa** [comment] 2022-07-29 12:54
@mzbroch does https://github.com/nautobot/nornir-nautobot/pull/56 fix this? Please try with the `develop` branch.

I would like to not have a PR that pins/downgrades code. The other plugins should move forward and update rather than require a library to pin and possibly get stale.

**Comment by jvanderaa** [comment] 2022-07-29 13:34
@jeffkala does develop work based on #56

**Comment by jeffkala** [comment] 2022-07-29 13:36
@qduk can you validate this fixed the problem in the environment you were testing?

**Comment by mzbroch** [comment] 2022-07-29 13:40
This is fair, however... This package dependency went in uncontrolled, because of lack of a proper pinning.

**Comment by jvanderaa** [comment] 2022-07-29 13:58
The `0*` is something that as the library we decided would be good to keep up to date. Should we look to move to a `*` instead? I would not expect to pin at `0.1.2`. That would then cause downstream effects from the project dependencies, not allowing for apps to leverage new versions of Netmiko and the inventory plugin.

**Comment by jvanderaa** [comment] 2022-08-09 16:49
This is confirmed fixed in develop.

**Closed by jvanderaa** 2022-08-09 16:49 UTC
